name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight (optional)
  push:
    branches:
      - main  # Adjust the branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.Hike-12 }}

      - name: Commit Snake Image
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Update snake image'
          add: 'dist/github-snake.svg'
