name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight to update the snake
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Generate Snake
        uses: platane/snk@v2
        with:
          github_user: 'Hike-12'  # Your GitHub username
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Snake Image
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Update snake image'
          add: 'snake.svg'
